### ISSUE TITLE
Can't parse unwrapped HTML

### ISSUE THREAD

**Issue by hugobessaa** [HenrikJoreteg/html-parse-stringify#16]
This breaks the parser in a weird way:

```html
You should be <strong>bold</strong>
```

I know `html-parse-stringify` focuses on parsing well-formed HTML, but I took a look at the code and supporting unwrapped text nodes could be trivial.

I can provide a PR if you think it's valid to support this use case.

Thanks for this little module 😄!

**Comment by HenrikJoreteg** [comment]
seems reasonable to me

**Comment by HenrikJoreteg** [comment]
have at it :)

**Comment by harunsmrkovic** [comment]
Also, it breaks for this HTML `<p>First</p> <p>Second</p>` (if there is space between tags)

**Comment by harunsmrkovic** [comment]
Isn't this the solution? #12

**Comment by hugobessaa** [comment]
Looks like

**Comment by DemonCloud** [comment]
LoL, Bad Guy Lib

**Comment by HenrikJoreteg** [comment]
@hugobessaa I've added you as a collaborator since I know you're using this. Feel free to merge and publish things (will add you on npm too).

**Comment by pconerly** [comment]
This issue is fixed so I'm closing :)
