### ISSUE TITLE
Incorrect parsing of (X)HTML comments

### ISSUE THREAD

**Issue by jollycic** [HenrikJoreteg/html-parse-stringify#17]
For a project I'm working on, I've been trying to parse generated HTML documents that contain comments, so I noticed that comment nodes are misinterpreted by the parser as non-void elements.

For instance, this code:

```
const HTML = require('html-parse-stringify');

let ast = HTML.parse("<!-- a comment --><p>a node containing text</p>");
let output = HTML.stringify(data);

```
returns the following AST:

```
[
  {
    "type": "tag",
    "name": "--",
    "voidElement": false,
    "attrs": {
      "a": "comment"
    },
    "children": [
      {
        "type": "tag",
        "name": "p",
        "voidElement": false,
        "attrs": {
          
        },
        "children": [
          {
            "type": "text",
            "content": "a node containing text"
          }
        ]
      }
    ]
  }
]
```
and thus the following stringified output:

```
<-- a="comment"><p>a node containing text</p></-->
```
IDK if this module is intended for parsing whole HTML documents (it seems to me that the typical use case is small HTML blocks), however it would be better if comments were treated properly.
Thanks.

**Comment by HenrikJoreteg** [comment]
this should be resolved in v2.0.0
