### ISSUE TITLE
phantomjs-prebuilt in dependencies =(

### ISSUE THREAD

**Issue by Tom910** [HenrikJoreteg/html-parse-stringify#23]
Version 1.0.3 have in dep phantomjs-prebuilt. It is create problem, becouse phantom have size > 90mb and loading with different servers

**Comment by Tom910** [comment]
Local version don't have last changes. And i can not send pr with fix

**Comment by beeplin** [comment]
Agree.

I don't see any code in here using phantomjs, so I am wondering why it is in dependencies. phantomjs is very difficult to install, so it would be nice to drop it~

**Comment by pconerly** [comment]
@beeplin I believe that `zuul` is using phantomjs, but tests with zuul haven't really been working for me? So there may be an opportunity to remove phantomjs after we diagnose the zuul issue, and whether we should keep zuul.

**Comment by HenrikJoreteg** [comment]
no longer using phantom at all as of v2.0.0
