### ISSUE TITLE
Publish the last few changes to npm

### ISSUE THREAD

**Issue by ericponto** [HenrikJoreteg/html-parse-stringify#37]
There have been some good changes in the past few months, but it doesn't look like they have been published to npm yet.

**Comment by effervescentia** [comment]
@HenrikJoreteg @latentflip is there anything we can do to get these changes released?
My company is looking to for this repository in order to publish the changes ourselves, but would obviously prefer to have it be published as part of this package officially

**Comment by HenrikJoreteg** [comment]
@effervescentia @ericponto thanks, y'all. Happy to add excited contributors here too. But please review this: https://github.com/HenrikJoreteg/html-parse-stringify/pull/38 trying to  bring this lib into this decade :)

**Comment by HenrikJoreteg** [comment]
all latest changes merged/published as `v2.0.0`
