### ISSUE TITLE
the problem of working with multilevel schemes

### ISSUE THREAD

**Issue by Pasha8914** [HenrikJoreteg/html-parse-stringify#39]
```<p>Some text.</p><figure><img src="some src" alt="some alt"/><figcaption></figcaption></figure><p>Some text</p>```

result => 
![image](https://user-images.githubusercontent.com/43392281/87263570-ecb24780-c500-11ea-968b-4f0160b26047.png)
if stringify  the result we ll have 

```<p>Some text.</p><figure><img src="some src" alt="some alt"/><figcaption></figcaption><p class="md-block-unstyled">Some text</p></figure>```

I think I fixed it locally, but I don’t like the solution
```    if (!isOpen || current.voidElement) {
      const isVoid = Boolean(current.voidElement);
      const parentName = arr[level - 1] && arr[level - 1].name;
      const curTag = tag.slice(2, -1);

      if (level > -1) {
        // if there is no parent node and that is the closing tag, I can assume that this is the closing tag of the parent  of previous block
        if (isVoid || !parentName || current.name === curTag) {
          level -= 1;
        }
      }

      if (!inComponent && nextChar !== "<" && nextChar) {
        parent = level === -1 ? result : arr[level].children;

        const endOfHtml = html.indexOf("<", start);
        const content = html.slice(
          start,
          endOfHtml === -1 ? undefined : endOfHtml,
        );
        if (!/^\s*$/.test(content)) {
          parent.push({
            type: "text",
            content,
          });
        }
      }
    }
    }```

**Comment by Pasha8914** [comment]
please pm me if you find a well solution
https://t.me/uhaubuhau894

**Comment by HenrikJoreteg** [comment]
@Pasha8914 I think this may have been resolved. Please try again using the latest version (2.1.1). Feel free to re-open if it's still an issue.
