### ISSUE TITLE
Not parsing correclty

### ISSUE THREAD

**Issue by stylesuxx** [HenrikJoreteg/html-parse-stringify#40]
This HTML string:
`<p><em>a</em></p><p>b</p><p><strong>c</strong></p><ul><li>d</li></ul><p>e</p>`

will generate the following AST:

```
[ { type: 'tag',
    name: 'p',
    voidElement: false,
    attrs: {},
    children: [ [Object], [Object], [Object] ] } ]
```

So basically the outermost p tag is considered to be wrapping all other elements.

**Comment by bblochkohl** [comment]
I have a similar problem, but it looks like, when having nested tags, the next following tag after the closing of nested parent, is included as children to the nested.

```
<div><h1>something</h1><p>go ahead</p><p>some more text</p></div>
<div><p>whatever</p></div>
```

will generate following

```
[ { type: 'tag',
    name: 'div',
    voidElement: false,
    attrs: {},
    children: [ {h1}, {p}, {p}, {div} ] 
} ]
```

**Comment by stylesuxx** [comment]
If you need a quick solution - I used [htmlparser2](https://www.npmjs.com/package/htmlparser2) instead.

**Comment by HenrikJoreteg** [comment]
From my understanding this has been fixed, thanks (sorry for the delay)
