### ISSUE TITLE
Seems that v2.0.1 it wasn't built

### ISSUE THREAD

**Issue by elrumordelaluz** [HenrikJoreteg/html-parse-stringify#42]
After upgrading obtains a 
```
Module not found: Can't resolve 'html-parse-stringify
```

same from [Unpkg](https://unpkg.com/html-parse-stringify@2.0.1/dist/html-parse-stringify.umd.js) 

![Screenshot 2021-03-01 at 15 20 26](https://user-images.githubusercontent.com/784056/109509869-a87cb300-7aa1-11eb-8903-db084a334a4e.png)

**Comment by brunoluan7** [comment]
My `html-parse-stringify` directory on `node_modules`  doesn't have `dist` folder as well.
Downgraded to 2.0.0 while this bug isn't fixed yet.

**Comment by elrumordelaluz** [comment]
still the same with [v2.0.2](https://unpkg.com/html-parse-stringify@2.0.2/dist/html-parse-stringify.umd.js)

**Comment by kachkaev** [comment]
@HenrikJoreteg 🙏

Lack of `dist` seems to be a blocker to https://github.com/i18next/react-i18next/issues/1275.

**Comment by HenrikJoreteg** [comment]
Sorry all! Total screw up on the publish on my part. I just added a prepublish script to make sure it always builds before publish. Should be good to go now please update to `2.0.3`.
