### ISSUE TITLE
Publish a new version to npm? The void elements fix is pretty important.

### ISSUE THREAD

**Issue by johnloy** [HenrikJoreteg/html-parse-stringify#8]
@HenrikJoreteg @latentflip 

First off, thanks for producing such a remarkably tiny html parser!

Now to the issue... unfortunately, v1.0.1 doesn't have the fixes for void elements in https://github.com/HenrikJoreteg/html-parse-stringify/commit/752871427aeb7d33d75243777ec1d9bafdb50fe8 and https://github.com/HenrikJoreteg/html-parse-stringify/commit/1c1254b0182190237c292a84c01d6c70fe9745bd

I just realized that with an html5 doctype, the default getter for innerHTML and outerHTML turns something like `<img />` into `<img>`. I'm trying to send output from outerHTML into the v1.0.1 parse function, but the element nesting in the AST gets pretty messed up as a result. Are you guys perhaps ready to publish a new version to npm anytime soon?

**Comment by HenrikJoreteg** [comment]
@johnloy just published `1.0.2` thanks John.
